dbt_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: postgres
      dbname: pipelines
      schema: public
      port: 5432
      threads: 16
